### ISSUE TITLE
This is not an issue, But would love ur help.. In making the necessary changes to the Waveform.lua to display audio waveforms.

### ISSUE THREAD

**Issue by chella1cm** [MikelSotomonte/mpv-waveform#1]
So far I tried making these changes
`local video_filters = mp.get_property_native("af")`
nothing happened, just displayed the video waveform as it should..

then tried this
`local video_filters = "lavfi=[aid1]showwaves=s=1280x720:mode=line:colors=white"`

this just gave me this error on mpv

> [waveform] Lua error: E:/Mpv/mpv/scripts/waveform.lua:73: bad argument #1 to 'pairs' (table expected, got string)

Would really appreciate your help.. 
Thank you

**Comment by MikelSotomonte** [comment]
Sadly I'm not super familiar with the code, I just kind of based it on other code by other people and a lot of trial and error. Good luck!
